name = "realtime-sync-engine-worker"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "REALTIME_SYNC_ENGINE"
class_name = "RealtimeSyncEngine"

[[migrations]]
tag = "v1"
new_classes = ["RealtimeSyncEngine"]
